### ISSUE TITLE
Wake words not working P4 / Respeaker 4mic

### ISSUE THREAD

**Issue by dave-parsons** [rhasspy/wyoming-satellite#117]
latest HA.  Wyoming integration setup complete and working.   Record and play tests on satellite working.

Wake words aren't triggering.   Looks like audio is being streamed in HA log - large sections of unreadable text.

Pi log shows this when I change the Wakeword via Voice Assistance setup on the HA side.

![image](https://github.com/rhasspy/wyoming-satellite/assets/37843022/884df9d2-82db-4962-9ad6-bbf4954c5d3b)

I have not setup VAD yet..   Any help / pointers appreciated

**Comment by llluis** [comment]
This error looks normal to me: server is resetting the connection when you change the Wakeword config. 

You should run satellite with the `--debug` flag and copy the output when runnning.
Are there any errors (in satellite or home assistant) when running?

**Comment by dave-parsons** [comment]
I am running debug on Sat.  I don't see any other errors.   I just can't get the wakeword to trigger anything.   I've been fiddling with changing pipeline settings / preferred, rebooting all.  Not sure where to look now.

**Comment by dave-parsons** [comment]
![image](https://github.com/rhasspy/wyoming-satellite/assets/37843022/b1850521-65cf-4796-8e5d-3e0d7587ceab)

**Comment by llluis** [comment]
What version of Home Assistant are you running? There's no error in the HA side?

It's weird the satellite not receiving the pong back.

**Comment by dave-parsons** [comment]
Core
2024.2.2
Supervisor
2024.01.1
Operating System
11.5
Frontend
20240207.1

**Comment by llluis** [comment]
Can you enable debug log on HA side? There was a bug logging in previous version which should be fixed now.

![image](https://github.com/rhasspy/wyoming-satellite/assets/708868/53605df7-9c16-4cc5-a581-b40e09269431)

(ignore the custom warning in my image as I'm running a modified version)

**Comment by llluis** [comment]
Remember you have do load full logs to see them.

![image](https://github.com/rhasspy/wyoming-satellite/assets/708868/d13dcfce-bfcd-4423-8417-52bd5ca2316f)

**Comment by dave-parsons** [comment]
I did a reboot and got this on HA side

Home Assistant Core
2024-02-16 19:53:53.618 DEBUG (MainThread) [homeassistant.components.wyoming.satellite] Running satellite task
2024-02-16 19:53:53.618 DEBUG (MainThread) [homeassistant.components.wyoming.satellite] Connecting to satellite at 192.168.1.176:10700
2024-02-16 19:53:53.675 DEBUG (MainThread) [homeassistant.components.wyoming.satellite] Connected to satellite
2024-02-16 19:53:53.702 DEBUG (MainThread) [homeassistant.components.wyoming.satellite] Received run information: RunPipeline(start_stage=<PipelineStage.WAKE: 'wake'>, end_stage=<PipelineStage.TTS: 'tts'>, name=None, restart_on_end=True, snd_format=None)
2024-02-16 19:53:53.702 DEBUG (MainThread) [homeassistant.components.wyoming.satellite] Starting pipeline Wyoming Sat Test from wake_word to tts
2024-02-16 19:53:53.932 DEBUG (MainThread) [homeassistant.components.wyoming.satellite] Receiving audio from satellite
2024-02-16 19:54:59.492 WARNING (MainThread) [homeassistant.components.wyoming.satellite] Satellite has been disconnected. Reconnecting in 10 second(s)
2024-02-16 19:55:02.493 DEBUG (MainThread) [homeassistant.components.wyoming.satellite] Disconnecting from satellite
2024-02-16 19:55:02.494 DEBUG (MainThread) [homeassistant.components.wyoming.satellite] Connecting to satellite at 192.168.1.176:10700
2024-02-16 19:55:02.624 DEBUG (MainThread) [homeassistant.components.wyoming.satellite] Failed to connect to satellite. Reconnecting in 10 second(s)
2024-02-16 19:55:12.626 DEBUG (MainThread) [homeassistant.components.wyoming.satellite] Connecting to satellite at 192.168.1.176:10700
2024-02-16 19:55:12.763 DEBUG (MainThread) [homeassistant.components.wyoming.satellite] Failed to connect to satellite. Reconnecting in 10 second(s)
2024-02-16 19:55:22.764 DEBUG (MainThread) [homeassistant.components.wyoming.satellite] Connecting to satellite at 192.168.1.176:10700
2024-02-16 19:55:22.767 DEBUG (MainThread) [homeassistant.components.wyoming.satellite] Failed to connect to satellite. Reconnecting in 10 second(s)
2024-02-16 19:55:32.768 DEBUG (MainThread) [homeassistant.components.wyoming.satellite] Connecting to satellite at 192.168.1.176:10700
2024-02-16 19:55:33.040 DEBUG (MainThread) [homeassistant.components.wyoming.satellite] Failed to connect to satellite. Reconnecting in 10 second(s)
2024-02-16 19:55:43.041 DEBUG (MainThread) [homeassistant.components.wyoming.satellite] Connecting to satellite at 192.168.1.176:10700
2024-02-16 19:55:43.183 DEBUG (MainThread) [homeassistant.components.wyoming.satellite] Failed to connect to satellite. Reconnecting in 10 second(s)
2024-02-16 19:55:53.183 DEBUG (MainThread) [homeassistant.components.wyoming.satellite] Connecting to satellite at 192.168.1.176:10700
2024-02-16 19:55:53.187 DEBUG (MainThread) [homeassistant.components.wyoming.satellite] Failed to connect to satellite. Reconnecting in 10 second(s)
2024-02-16 19:56:03.189 DEBUG (MainThread) [homeassistant.components.wyoming.satellite] Connecting to satellite at 192.168.1.176:10700
2024-02-16 19:56:03.194 DEBUG (MainThread) [homeassistant.components.wyoming.satellite] Connected to satellite
2024-02-16 19:56:03.201 DEBUG (MainThread) [homeassistant.components.wyoming.satellite] Received run information: RunPipeline(start_stage=<PipelineStage.WAKE: 'wake'>, end_stage=<PipelineStage.TTS: 'tts'>, name=None, restart_on_end=True, snd_format=None)
2024-02-16 19:56:03.201 DEBUG (MainThread) [homeassistant.components.wyoming.satellite] Starting pipeline Wyoming Sat Test from wake_word to tts
2024-02-16 19:56:03.263 DEBUG (MainThread) [homeassistant.components.wyoming.satellite] Receiving audio from satellite

**Comment by llluis** [comment]
Looks like everything is working as supposed, except the server can't maintaint the connection with the satellite.
Anything you can think which could affect that?

**Comment by dave-parsons** [comment]
I'm stumped.   Connection only broken because I rebooted.   Is wakeword detection happening on satellite or HA server?   Much rather it be on the sat.  That was working on this device using rhasspy but now no.

**Comment by llluis** [comment]
Right now as per your logs and command line, it's happening in HA.
 
To run it in satellite, you have to install openwakeword in satellite and modify your command line to connect to it.
Check the tutorial here: https://github.com/rhasspy/wyoming-satellite/blob/master/docs/tutorial_2mic.md#local-wake-word-detection

**Comment by llluis** [comment]
> I'm stumped. Connection only broken because I rebooted. Is wakeword detection happening on satellite or HA server? Much rather it be on the sat. That was working on this device using rhasspy but now no.

I didn't notice the connection lost was after a minute and due the reboot.
Well, then it should be working (even if wake during by HA).

**Comment by dave-parsons** [comment]
Finally got it working with wake on the satellite.   Still don't know why not working on the HA side, but prefer satellite anyway. 
 
 Thank you @llluis for the help.  for anyone interested, here's my resulting service configurations on satellite - took a bit to get it figured out.

Satellite Service
```
[Unit]
Description=Wyoming Office Satellite
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
ExecStart=/home/pi/wyoming-satellite/script/run \
--name 'Office satellite' \
--uri 'tcp://0.0.0.0:10700' \
--mic-command 'arecord -D plughw:CARD=seeed4micvoicec,DEV=0 -r 16000 -c 1 -f S16_LE -t raw' \
--snd-command 'aplay -D plughw:CARD=Headphones,DEV=0 -r 22050 -c 1 -f S16_LE -t raw' \
--wake-uri 'tcp://127.0.0.1:10400' \
--wake-word-name 'hey_jarvis'
WorkingDirectory=/home/pi/wyoming-satellite
Restart=always
RestartSec=1

[Install]
WantedBy=default.target
```
Wake Service

```
[Unit]
Description=Wyoming openWakeWord

[Service]
Type=simple
ExecStart=/home/pi/wyoming-openwakeword/script/run --uri 'tcp://127.0.0.1:10400'
WorkingDirectory=/home/pi/wyoming-openwakeword
Restart=always
RestartSec=1

[Install]
WantedBy=default.target
```
